### ISSUE TITLE
QE: QED circuits

### ISSUE THREAD

**Issue by p3drotto** [quantum-engineering-polito/CourseNotes#62]

**Comment by gamberoillecito** [comment]
- [ ] eq (8), I think the resonator freq is only omega_r
- [ ] line 164, capitalize title
- [ ] line 140, explain better what is the dispersive regime 
- [ ] line 132 seems a supercazzola
- [ ] eq (7), maybe change = with ~=
- [ ] line 114, tu
- [ ] line 67, phenomena
- [ ] line 64, transmont
- [ ] line 39, highlight the condition for the transmission
- [ ] missing some \n
- [ ] eq (2) missing "t" inside cos
- [ ] line 27, maybe from |1> to |0>

**Comment by p3drotto** [comment]
1. eq (8) omega_r is the bare resonator frequency, the one without the qubit. When you couple with the qubit, in the dispersive regime you get a phase shift in the **actual** resonator frequency, that depends on the state of the qubit. This comes mathematically from equation 8, where you see that everything that multiplies the number operator (hbar times what I indicated as frequency) depends on the operator sigma_z.
2. done
3. Look if now sounds better.
4. He told it in class. And actually imo is a nice interpretation.
5. Idk I like it as it is, because after the approximation the hamiltonian is equal to something, not almost equal to something.
6. done
7. changed with "effect"
8. done
9. done
10. where? If you spot it you can change it
11. done
12. Actually with a frequency that matches the energy difference of a two level system you can go: from 0 to 1, from 1 to 0 and anything in between (Rabi oscillations)
